# Generated by Django 4.2.7 on 2023-11-18 21:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ci', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('f_nacimiento', models.DateField()),
                ('ubicacion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=11)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('minutos_favor', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('f_creacion', models.DateField(auto_now_add=True)),
                ('f_actualizacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-f_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cant_controles', models.PositiveIntegerField()),
                ('serial', models.CharField(blank=True, max_length=30, null=True)),
                ('ocupada', models.BooleanField(default=False)),
                ('f_actualizacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Consola',
                'verbose_name_plural': 'Consolas',
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('f_compra', models.DateField(auto_now_add=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('accion', 'Acción'), ('aventura', 'Aventura'), ('deportes', 'Deportes'), ('estrategia', 'Estrategia'), ('otros', 'Otros')], max_length=10)),
                ('tipo', models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital')], max_length=7)),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('h_inicio', models.TimeField(auto_now_add=True)),
                ('h_final', models.TimeField()),
                ('f_sesion', models.DateTimeField(auto_now_add=True)),
                ('minutos_regalo', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cant_minutos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cant_personas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Local.cliente')),
                ('id_consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Local.consola')),
            ],
            options={
                'verbose_name': 'Sesion',
                'verbose_name_plural': 'Sesiones',
            },
        ),
        migrations.AddField(
            model_name='consola',
            name='juegos_instalados',
            field=models.ManyToManyField(to='Local.juego'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fh_compra', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Local.cliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fh_compra'],
            },
        ),
    ]
