# Generated by Django 4.2.7 on 2023-11-18 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='minutos_favor',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
