# Generated by Django 4.2.7 on 2023-11-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Caja", "0003_remove_cuenta_compras_remove_cuenta_sesiones"),
        ("Local", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="id_cuenta",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Caja.cuenta"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sesion",
            name="id_cuenta",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Caja.cuenta"
            ),
            preserve_default=False,
        ),
    ]
