# Generated by Django 4.2.7 on 2023-11-23 18:26

import Local.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Local", "0002_compra_id_cuenta_sesion_id_cuenta"),
    ]

    operations = [
        migrations.AddField(
            model_name="sesion",
            name="abierto",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="sesion",
            name="id_consola",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Local.consola",
                validators=[Local.models.consola_ocupada],
            ),
        ),
    ]
