# Generated by Django 4.2.7 on 2023-11-24 20:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Caja", "0006_alter_cierre_fh_cierre"),
        (
            "Inventario",
            "0003_alter_entrada_cant_ingresada_alter_entrada_costo_and_more",
        ),
        ("Local", "0004_alter_compra_cantidad_alter_compra_monto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fh_venta", models.DateTimeField(auto_now_add=True)),
                (
                    "cantidad",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Local.cliente"
                    ),
                ),
                (
                    "id_cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Caja.cuenta"
                    ),
                ),
                ("productos", models.ManyToManyField(to="Inventario.producto")),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["-fh_venta"],
            },
        ),
        migrations.DeleteModel(
            name="Compra",
        ),
    ]
