# Generated by Django 4.2.7 on 2023-12-04 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Inventario", "0005_alter_producto_precio_compra"),
        ("Local", "0005_venta_delete_compra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="monto",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="productos",
        ),
        migrations.AddField(
            model_name="venta",
            name="id_producto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Inventario.producto",
            ),
            preserve_default=False,
        ),
    ]
