# Generated by Django 4.2.7 on 2023-12-04 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Caja", "0006_alter_cierre_fh_cierre"),
        ("Local", "0006_remove_venta_monto_remove_venta_productos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="id_cuenta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Caja.cuenta",
            ),
        ),
    ]
