# Generated by Django 4.2.7 on 2023-11-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Local', '0002_alter_cliente_minutos_favor'),
        ('Caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Local.compra'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='sesiones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Local.sesion'),
        ),
    ]
