# Generated by Django 4.2.7 on 2023-11-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Inventario", "0001_initial"),
        ("Caja", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuenta",
            name="compras",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Inventario.producto",
            ),
        ),
    ]
