# Generated by Django 4.2.7 on 2023-11-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Caja", "0002_alter_cuenta_compras"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuenta",
            name="compras",
        ),
        migrations.RemoveField(
            model_name="cuenta",
            name="sesiones",
        ),
    ]
