# Generated by Django 4.2.7 on 2023-11-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Caja", "0003_remove_cuenta_compras_remove_cuenta_sesiones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="fh_actualizacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
