# Generated by Django 4.2.7 on 2023-11-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Caja", "0004_alter_variable_fh_actualizacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuenta",
            name="monto_deberbs",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="montobs",
        ),
    ]
