# Generated by Django 4.2.7 on 2023-11-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Caja", "0005_remove_cuenta_monto_deberbs_remove_pago_montobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cierre",
            name="fh_cierre",
            field=models.DateField(),
        ),
    ]
