# Generated by Django 4.2.7 on 2023-12-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Caja", "0006_alter_cierre_fh_cierre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cierre",
            name="id",
        ),
        migrations.AlterField(
            model_name="cierre",
            name="fh_cierre",
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
