# Generated by Django 4.2.7 on 2023-12-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Caja", "0007_remove_cierre_id_alter_cierre_fh_cierre"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuenta",
            name="fh_ultimo_pago",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
