# Generated by Django 4.2.7 on 2023-12-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Caja", "0008_cuenta_fh_ultimo_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="cierre",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cierre",
            name="fh_cierre",
            field=models.DateField(unique=True),
        ),
    ]
