# Generated by Django 4.2.7 on 2023-11-28 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Inventario",
            "0003_alter_entrada_cant_ingresada_alter_entrada_costo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="cant_invent",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
