# Generated by Django 4.2.7 on 2023-12-04 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventario", "0005_alter_producto_precio_compra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="cant_invent",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
