# Generated by Django 4.2.7 on 2023-12-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Inventario", "0006_alter_producto_cant_invent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entrada",
            old_name="costo",
            new_name="costo_punidad",
        ),
    ]
