# Generated by Django 4.2.7 on 2023-12-04 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventario", "0007_rename_costo_entrada_costo_punidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="costo_envio",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="entrada",
            name="costo_mercancia",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entrada",
            name="costo_punidad",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
