# Generated by Django 4.2.7 on 2024-08-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Local', '0002_alter_cliente_ci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='precio_compra',
            new_name='precio_compra_dolar',
        ),
    ]
