# Generated by Django 4.2.7 on 2024-07-27 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Caja', '0001_initial'),
        ('Local', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Local.cliente'),
        ),
    ]
