# Generated by Django 4.2.7 on 2024-07-27 19:43

from django.db import migrations
from Caja.models import Variable

def create_initial_data_model_variable(apps, schema_editor):
    # Crea los registros iniciales
    precio = Variable(nombre='Precio de la Hora', valor='1.0', tipo_dato='Decimal')
    cambio = Variable(nombre='Cambio Dolar', valor='40', tipo_dato='Decimal')
    precio.save()
    cambio.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0001_initial'),
        ('Caja', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data_model_variable),
    ]
