# Generated by Django 4.2.7 on 2024-08-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0003_auto_20240727_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='monto_deberdolar',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='montodolar',
        ),
        migrations.AddField(
            model_name='cierre',
            name='total_minutos',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='monto_deber',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
