# Generated by Django 4.2.7 on 2024-08-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0004_remove_cuenta_monto_deberdolar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='monto_deber_dolar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='monto_pagado_dolar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
