# Generated by Django 4.2.7 on 2024-08-23 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0005_cuenta_monto_deber_dolar_cuenta_monto_pagado_dolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_dolar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
