# Generated by Django 4.2.7 on 2024-08-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0007_alter_pago_monto_alter_pago_monto_dolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre',
            name='total_jugadores',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=3),
        ),
    ]
